[package]
name = "test-protobuf"
version = "0.1.0"
edition = "2021"


[dependencies]
tonic = "0.7"
prost = "0.10"
prost-types = "0.10"

runtime = {path = "runtime"}
test-protobuf-derive = {path = "src/derive"}



[build-dependencies]
tonic-build = { version = "0.7", features = ["prost"] }
